EnvironmentConfigurationMetadata:
  Description: Configuration for apester destination client prod environment
  DateCreated: '1465979775000'
  DateModified: '1465979775000'
SolutionStack: 64bit Amazon Linux 2016.03 v2.1.6 running Docker 1.11.2
OptionSettings:
  aws:elasticbeanstalk:command:
    BatchSize: '30'
    BatchSizeType: Percentage
  aws:elasticbeanstalk:sns:topics:
    Notification Endpoint: https://api.opsgenie.com/v1/json/cloudwatch?apiKey=60882956-1498-406b-a0d1-1c1ac2af0c12
    Notification Protocol: https
  aws:elb:policies:
    ConnectionDrainingEnabled: true
    ConnectionDrainingTimeout: '5'
  aws:elb:healthcheck:
    UnhealthyThreshold: '2'
    Timeout: '4'
    HealthyThreshold: '2'
    Interval: '300'
  aws:elb:loadbalancer:
     LoadBalancerHTTPSPort: '443'
     CrossZone: true
     SSLCertificateId: arn:aws:iam::148612970729:server-certificate/cloudfront/apester-2016
     SecurityGroups: sg-48005532
     ManagedSecurityGroup: sg-48005532
  aws:elasticbeanstalk:environment:
    ServiceRole: aws-elasticbeanstalk-service-role
  aws:elasticbeanstalk:application:
    Application Healthcheck URL: ''
  aws:autoscaling:trigger:
     LowerThreshold: '2'
     MeasureName: Latency
     UpperThreshold: '5'
     Unit: Seconds
  aws:elasticbeanstalk:healthreporting:system:
    AWSEBHealthdGroupId: e8423e88-2d0b-4b3c-977e-f52c9252bef5
    SystemType: enhanced
  aws:autoscaling:launchconfiguration:
    IamInstanceProfile: aws-elasticbeanstalk-ec2-role
    InstanceType: c4.large
    EC2KeyName: CoreBackend-2016
    SecurityGroups: sg-48005532
  aws:autoscaling:asg:
    MinSize: '2'
    MaxSize: '6'
  aws:autoscaling:updatepolicy:rollingupdate:
    RollingUpdateType: Health
    RollingUpdateEnabled: true
  aws:ec2:vpc:
    VPCId: vpc-a5e78cc1
    Subnets: subnet-e449bbbc,subnet-3af55273
    ELBSubnets: subnet-e449bbbc,subnet-3af55273
    AssociatePublicIpAddress: true
EnvironmentTier:
  Type: Standard
  Name: WebServer
Extensions:
  DestinationApiProdHealth.EBConsoleSnippet:
    Order: 500
    SnippetContents:
      Resources:
        DestinationApiProdHealth:
          Type: AWS::CloudWatch::Alarm
          Properties:
            AlarmActions:
            - arn:aws:sns:us-east-1:148612970729:ElasticBeanstalkNotifications-Environment-destination-client-prod
            MetricName: EnvironmentHealth
            ComparisonOperator: GreaterThanOrEqualToThreshold
            AlarmDescription: Destination Api Prod Environment Health
            Statistic: Maximum
            Period: 60
            Dimensions:
            - Value:
                Ref: AWSEBEnvironmentName
              Name: EnvironmentName
            EvaluationPeriods: 1
            InsufficientDataActions:
            - arn:aws:sns:us-east-1:148612970729:ElasticBeanstalkNotifications-Environment-destination-client-prod
            Namespace: AWS/ElasticBeanstalk
            OKActions:
            - arn:aws:sns:us-east-1:148612970729:ElasticBeanstalkNotifications-Environment-destination-client-prod
            Threshold: 7
  DestinationApiProdCPUProblem.EBConsoleSnippet:
    Order: 500
    SnippetContents:
      Resources:
        DestinationApiProdCPUProblem:
          Type: AWS::CloudWatch::Alarm
          Properties:
            AlarmActions:
            - arn:aws:sns:us-east-1:148612970729:DestinationApiProdCPUProblem
            MetricName: CPUUtilization
            ComparisonOperator: GreaterThanThreshold
            Statistic: Average
            Period: 300
            Dimensions:
            - Value:
                Ref: AWSEBAutoScalingGroup
              Name: AutoScalingGroupName
            EvaluationPeriods: 1
            InsufficientDataActions: []
            Namespace: AWS/EC2
            OKActions:
            - arn:aws:sns:us-east-1:148612970729:DestinationApiProdCPUProblem
            Threshold: 50
  DestinationApiProdMaxLatency.EBConsoleSnippet:
    Order: 500
    SnippetContents:
      Resources:
        DestinationApiProdMaxLatency:
          Type: AWS::CloudWatch::Alarm
          Properties:
            AlarmActions:
            - arn:aws:sns:us-east-1:148612970729:DestinationApiProdMaxLatency
            MetricName: Latency
            ComparisonOperator: GreaterThanThreshold
            Statistic: Average
            Period: 300
            Dimensions:
            - Value:
                Ref: AWSEBLoadBalancer
              Name: LoadBalancerName
            EvaluationPeriods: 1
            InsufficientDataActions: []
            Namespace: AWS/ELB
            OKActions:
            - arn:aws:sns:us-east-1:148612970729:DestinationApiProdMaxLatency
            Threshold: 7
AWSConfigurationTemplateVersion: 1.1.0.0
